# Override Nixpacks default behavior to fix npm ci issues
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
# Skip default npm ci and use npm install instead
cmd = "npm install --legacy-peer-deps"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"