services:
  - type: web
    name: fairgo-production
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start:render
    healthCheckPath: /api/health
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fairgo-database
          property: connectionString

databases:
  - name: fairgo-database
    plan: free
    databaseName: fairgo
    user: fairgo_user

# Optional: Background worker for processing tasks
# - type: worker
#   name: fairgo-worker
#   env: node
#   buildCommand: npm run render-build
#   startCommand: npm run worker
#   envVars:
#     - key: NODE_ENV
#       value: production
#     - key: DATABASE_URL
#       fromDatabase:
#         name: fairgo-database
#         property: connectionString